drop table if exists notice;

create table notice
(
    id            bigint generated by default as identity,
    contents      varchar(255),
    deleted       boolean,
    deleted_at    timestamp,
    hits          bigint,
    likes         bigint,
    registered_at timestamp,
    title         varchar(255),
    updated_at    timestamp,
    primary key (id)
);